/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class main extends javax.swing.JFrame {

    private int userS=0;
    private int compS=0;
    private int games=5;
    private int choice;
    public main() {
        initComponents();
        repeat.setEnabled(false);
        C.setEnabled(false);
        u.setEnabled(false);
        afficheC.setEnabled(false);
        afficherU.setEnabled(false);
        pp.setEnabled(false);
        p.setEnabled(false);
        s.setEnabled(false);
        Cscore.setEnabled(false);
        Uscore.setEnabled(false);
        gamesL.setEnabled(false);
        jLabel2.setEnabled(false);
        same.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        s = new javax.swing.JButton();
        p = new javax.swing.JButton();
        pp = new javax.swing.JButton();
        u = new javax.swing.JLabel();
        Uscore = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        Cscore = new javax.swing.JLabel();
        afficheC = new javax.swing.JLabel();
        afficherU = new javax.swing.JLabel();
        repeat = new javax.swing.JButton();
        star = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gamesL = new javax.swing.JLabel();
        same = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        s.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p.png"))); // NOI18N
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pp.png"))); // NOI18N
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        pp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s.png"))); // NOI18N
        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });

        u.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1481742709_icons_user.png"))); // NOI18N

        Uscore.setFont(new java.awt.Font("Harlow Solid Italic", 1, 16)); // NOI18N

        C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1481742880_multimedia-37.png"))); // NOI18N

        Cscore.setFont(new java.awt.Font("Harlow Solid Italic", 1, 16)); // NOI18N

        repeat.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        repeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1481742748_icons_update.png"))); // NOI18N
        repeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatActionPerformed(evt);
            }
        });

        star.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        star.setText("star");
        star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N
        jLabel2.setText("games left :");

        gamesL.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N

        same.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N
        same.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(u, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Uscore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(94, 94, 94)
                                        .addComponent(pp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(afficherU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53)
                                                .addComponent(afficheC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(129, 129, 129)
                                                .addComponent(same, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Cscore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(C)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(repeat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(star, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gamesL, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cscore, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(u)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Uscore, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afficherU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afficheC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(same, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gamesL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(star, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repeat, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        same.setText("");
        afficherU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p.png"))); 
        choice=(int) (Math.random()*3)+1;
        if(choice==1){
        afficheC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p.png")));
        same.setText("same!");
        }else{
        if(choice==2){
            afficheC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pp.png")));
            compS++;
            games--;
            Cscore.setText("score : "+compS);
            Uscore.setText("score : "+userS);
            gamesL.setText(""+games);
        }else{
            afficheC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s.png")));
            userS++;
            games--;
            Cscore.setText("score : "+compS);
            Uscore.setText("score : "+userS);
            gamesL.setText(""+games);
        }
        }
        if(games==0){
            same.setEnabled(false);
        star.setEnabled(false);
        pp.setEnabled(false);
        p.setEnabled(false);
        s.setEnabled(false);
        afficheC.setEnabled(false);
        afficherU.setEnabled(false);
        gamesL.setEnabled(false);
        jLabel2.setEnabled(false);
        
        if(userS>compS){
            Cscore.setText("loser");
            Uscore.setText("winner");
        
        }else{
        
        Cscore.setText("winner");
        Uscore.setText("loser");
        }
        }
    }//GEN-LAST:event_sActionPerformed

    private void repeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatActionPerformed
        afficheC.setIcon(null);
        afficherU.setIcon(null);
        star.setEnabled(true);
        C.setEnabled(true);
        u.setEnabled(true);
        afficheC.setEnabled(true);
        afficherU.setEnabled(true);
        pp.setEnabled(true);
        p.setEnabled(true);
        s.setEnabled(true);
        Cscore.setEnabled(true);
        Uscore.setEnabled(true);
        gamesL.setEnabled(true);
        jLabel2.setEnabled(true);
        same.setEnabled(true);
        userS=0;
        compS=0;
        games=5;
        Cscore.setText("score : "+compS);
        Uscore.setText("score : "+userS);
        gamesL.setText(""+games);
    }//GEN-LAST:event_repeatActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        same.setText("");
        afficherU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pp.png"))); 
        choice=(int) (Math.random()*3)+1;
        if(choice==1){
            afficheC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p.png")));
            userS++;
            games--;
            Cscore.setText("score : "+compS);
            Uscore.setText("score : "+userS);
            gamesL.setText(""+games);
        
        }else{
        if(choice==2){
            afficheC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pp.png")));
            same.setText("same!");
        }else{
            afficheC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s.png")));
            compS++;
            games--;
            Cscore.setText("score : "+compS);
            Uscore.setText("score : "+userS);
            gamesL.setText(""+games);
        }
        }
        if(games==0){
            same.setEnabled(false);
        star.setEnabled(false);
        pp.setEnabled(false);
        p.setEnabled(false);
        s.setEnabled(false);
        afficheC.setEnabled(false);
        afficherU.setEnabled(false);
        gamesL.setEnabled(false);
        jLabel2.setEnabled(false);
        
        if(userS>compS){
            Cscore.setText("loser");
            Uscore.setText("winner");
        
        }else{
        
        Cscore.setText("winner");
        Uscore.setText("loser");
        }
        }
    }//GEN-LAST:event_pActionPerformed

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        same.setText("");
        afficherU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s.png")));
         choice=(int) (Math.random()*3)+1;
        if(choice==1){
            afficheC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p.png")));
            compS++;
            games--;
            Cscore.setText("score : "+compS);
            Uscore.setText("score : "+userS);
            gamesL.setText(""+games);
        
        }else{
        if(choice==2){
            afficheC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pp.png")));
            userS++;
            games--;
            Cscore.setText("score : "+compS);
            Uscore.setText("score : "+userS);
            gamesL.setText(""+games);
        }else{
            afficheC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s.png")));
            same.setText("same!");
        }
        }
        if(games==0){
            same.setEnabled(false);
        star.setEnabled(false);
        pp.setEnabled(false);
        p.setEnabled(false);
        s.setEnabled(false);
        afficheC.setEnabled(false);
        afficherU.setEnabled(false);
        gamesL.setEnabled(false);
        jLabel2.setEnabled(false);
        
        if(userS>compS){
            Cscore.setText("loser");
            Uscore.setText("winner");
        
        }else{
        
        Cscore.setText("winner");
        Uscore.setText("loser");
        }
        }
    }//GEN-LAST:event_ppActionPerformed

    private void starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starActionPerformed
        same.setEnabled(true);
        repeat.setEnabled(true);
        C.setEnabled(true);
        u.setEnabled(true);
        afficheC.setEnabled(true);
        afficherU.setEnabled(true);
        pp.setEnabled(true);
        p.setEnabled(true);
        s.setEnabled(true);
        Cscore.setEnabled(true);
        Uscore.setEnabled(true);
        Cscore.setText("score : "+compS);
        Uscore.setText("score : "+userS);
        gamesL.setEnabled(true);
        gamesL.setText(games+"");
    }//GEN-LAST:event_starActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel C;
    private javax.swing.JLabel Cscore;
    private javax.swing.JLabel Uscore;
    private javax.swing.JLabel afficheC;
    private javax.swing.JLabel afficherU;
    private javax.swing.JLabel gamesL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton p;
    private javax.swing.JButton pp;
    private javax.swing.JButton repeat;
    private javax.swing.JButton s;
    private javax.swing.JLabel same;
    private javax.swing.JButton star;
    private javax.swing.JLabel u;
    // End of variables declaration//GEN-END:variables
}
